### ISSUE TITLE
'ghas:error TypeError' on 'yarn run getRepos'

### ISSUE THREAD

**Issue by matb42** [NickLiffen/ghas-enablement#114]
Hey, I'm having an issue getting `repos.json` populated due to`ghas:error TypeError: Cannot read properties of undefined (reading 'includes')`, and was curious if anyone had seen this or is familiar with the issue? Output and .env are below:

```
# AUTH: GitHub PAT Configuration
GITHUB_API_TOKEN=<gh_tkn>

# Set one of the GITHUB_ENTERPRISE or GITHUB_ORG variables.
GITHUB_ENTERPRISE=
GITHUB_ORG=<OurOrg>

# If you are filtering by language, set the language here. Please use either: javascript, typescript, go, python, ruby, c#, c++, java, or kotlin
LANGUAGE_TO_CHECK=javascript

# Debug Configuration
DEBUG=ghas:*

# GHES Configuration
GHES=false
GHES_SERVER_BASE_URL=

# Temp working directory. This path needs to already exist and follow linux style paths. c:\ghas\tmp == ghas/tmp
TEMP_DIR=<my_path> 
```

```
% yarn run getRepos
yarn run v1.22.19
warning ../../package.json: No license field
$ npm run build && node ./lib/getRepos.js

> github-helper@1.0.0 build
> npx tsc

  ghas:inform Could not find file: ./bin/organizations.json. Assuming no organizations have been collected. +0ms
  ghas:inform Collecting repositories for <OurOrg> +1ms
  ghas:inform This is org number 1 of 1 +0ms
  ghas:inform Repo Name: <x> Permission: <x> Archived: false Language: JavaScript Visibility: PRIVATE +1s
.
.
.
  ghas:inform Repo Name: <x> Permission: <x> Archived: true Language: Python Visibility: PRIVATE +0ms
  ghas:inform Found 66 repositories that met the valid criteria in the organisation <OurOrg>. Out of 100. +0ms
  ghas:error TypeError: Cannot read properties of undefined (reading 'includes')
  ghas:error     at getRepositoryInOrganizationPaginate (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:45:20)
  ghas:error     at async paginateQuery (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:73:22)
  ghas:error     at async collectRepos (/Users/mattb/workspace/ghas-enablement/lib/utils/collectRepos.js:21:40)
  ghas:error     at async start (/Users/mattb/workspace/ghas-enablement/lib/getRepos.js:34:9) +0ms
  ghas:error TypeError: Cannot read properties of undefined (reading 'includes')
  ghas:error     at getRepositoryInOrganizationPaginate (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:45:20)
  ghas:error     at async paginateQuery (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:73:22)
  ghas:error     at async collectRepos (/Users/mattb/workspace/ghas-enablement/lib/utils/collectRepos.js:21:40)
  ghas:error     at async start (/Users/mattb/workspace/ghas-enablement/lib/getRepos.js:34:9) +0ms
  ghas:error TypeError: Cannot read properties of undefined (reading 'includes')
  ghas:error     at getRepositoryInOrganizationPaginate (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:45:20)
  ghas:error     at async paginateQuery (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:73:22)
  ghas:error     at async collectRepos (/Users/mattb/workspace/ghas-enablement/lib/utils/collectRepos.js:21:40)
  ghas:error     at async start (/Users/mattb/workspace/ghas-enablement/lib/getRepos.js:34:9) +0ms
  ghas:error TypeError: Cannot read properties of undefined (reading 'includes')
  ghas:error     at getRepositoryInOrganizationPaginate (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:45:20)
  ghas:error     at async paginateQuery (/Users/mattb/workspace/ghas-enablement/lib/utils/paginateQuery.js:73:22)
  ghas:error     at async collectRepos (/Users/mattb/workspace/ghas-enablement/lib/utils/collectRepos.js:21:40)
  ghas:error     at async start (/Users/mattb/workspace/ghas-enablement/lib/getRepos.js:34:9) +0ms
✨  Done in 3.56s.`

**Comment by joshjohanning** [comment]
The only way I could re-create this issue is if I didn't have this line in my `.env` file:

```
# Specify what to enable. The default will be codescanning. An example is: ENABLE_ON=codescanning,secretscanning,dependabot,dependabotupdates,pushprotection,actions
ENABLE_ON=codescanning,secretscanning,dependabot,dependabotupdates,pushprotection
```

Not sure if the `.env` file you shared was a partial or the whole thing, but perhaps add back in that line with what features you want to have enabled.

**Comment by matb42** [comment]
@joshjohanning that was the issue! This is fixed and working now, thanks a million :) I didn't realize that was still needed in the getRepos phase.

**Comment by joshjohanning** [comment]
> @joshjohanning that was the issue! This is fixed and working now, thanks a million :) I didn't realize that was still needed in the getRepos phase.

Great!

And as you see in the json that is outputted, each feature has a true/false so you could selectively enable features on the list of repositories. 

```json

[
  {
    "login": "string <org>",
    "repos":
    [
      {
        "createIssue": "boolean",
        "enableCodeScanning": "boolean",
        "enableDependabot": "boolean",
        "enableDependabotUpdates": "boolean",
        "enablePushProtection": "boolean",
        "enableSecretScanning": "boolean",
        "enableActions": "boolean",
        "repo": "string <org/repo>",
      }
    ]
  }
]

```
